[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.goerli]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
libraries = [
    './src/libraries/Actions.sol:Actions:0x26d74f09dc17b6239310aa27c213394acb2ae0ca'
]
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.bnbt]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
libraries = [
    './src/libraries/Actions.sol:Actions:0x781d0a455020024da046f823d9ea076b76a873f3'
]
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.mainnet]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
libraries = [
    './src/libraries/Actions.sol:Actions:0x8ccbe07f1e12a61e4fbb3a1895d35dce001ff73a'
]
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.nova]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
libraries = [
    './src/libraries/Actions.sol:Actions:0xf1944eca9a85a0ba3db0721343289de758c70ae4'
]
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.bnb]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
libraries = [
    './src/libraries/Actions.sol:Actions:0x8ccbe07f1e12a61e4fbb3a1895d35dce001ff73a'
]
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config