[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.goerli]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
libraries = [
    './src/libraries/Actions.sol:Actions:0x26d74f09dc17b6239310aa27c213394acb2ae0ca'
]
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.bnbt]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
libraries = [
    './src/libraries/Actions.sol:Actions:0x5551336Ee5aa3b3ccF6BA11bdBfDcF8F0758b5d6'
]
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.mainnet]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.nova]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
libraries = [
    './src/libraries/Actions.sol:Actions:0x16c9471c076cd38e282ee7adc158b510d17c0951'
]
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config